# Generated by Django 2.0 on 2018-02-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Телефон')),
                ('type', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Тип')),
                ('city', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Город')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Оставлена')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
