# Generated by Django 2.0 on 2018-02-02 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Описание')),
                ('price', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Дополнительный товар',
                'verbose_name_plural': 'Дополнительные товар',
            },
        ),
        migrations.CreateModel(
            name='ExtraProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/products/')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ExtraProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Название')),
                ('price', models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена')),
                ('toughness', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Жесткость')),
                ('press', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='MAX нагрузка')),
                ('height', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Высота')),
                ('date', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Срок службы')),
                ('guaranty', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Гарантия')),
            ],
            options={
                'verbose_name': 'Матрас',
                'verbose_name_plural': 'Матрасы',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/products/')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Размер')),
                ('price', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Цена')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Пружинный блок',
                'verbose_name_plural': 'Пружинные блок',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductGroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='spring',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductSpring'),
        ),
    ]
