# Generated by Django 2.0 on 2018-02-02 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spring',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductSpring', verbose_name='Тип пружины'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Подзаголовок'),
        ),
    ]
