# Generated by Django 2.0 on 2018-02-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180202_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraproduct',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена'),
        ),
    ]
