# Generated by Django 2.0 on 2018-02-02 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180202_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Слой')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Состав по слоям',
                'verbose_name_plural': 'Составы по слоям',
            },
        ),
    ]
