# Generated by Django 2.0 on 2018-02-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productmaterials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraproduct',
            options={'verbose_name': 'Дополнительный товар', 'verbose_name_plural': 'Дополнительные товары'},
        ),
        migrations.AlterModelOptions(
            name='productmaterials',
            options={'verbose_name': 'Состав по слоям', 'verbose_name_plural': 'Состав по слоям'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
