# Generated by Django 2.0.2 on 2018-02-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180202_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraproduct',
            options={'verbose_name': 'Дополнительный товар', 'verbose_name_plural': '**Дополнительные товары'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Матрас', 'verbose_name_plural': '*Матрасы'},
        ),
        migrations.RemoveField(
            model_name='productsizes',
            name='size',
        ),
        migrations.AddField(
            model_name='productsizes',
            name='length',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='productsizes',
            name='width',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Ширина'),
        ),
    ]
