# Generated by Django 2.0.2 on 2018-02-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180202_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Ссылка на основной сайт'),
        ),
        migrations.AlterField(
            model_name='productsizes',
            name='length',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Длина'),
        ),
    ]
