# Generated by Django 2.0.2 on 2018-02-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180208_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproduct',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Ссылка на основной сайт'),
        ),
    ]
