# Generated by Django 2.0.2 on 2018-02-17 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_extraproduct_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Слой')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ExtraProduct')),
            ],
            options={
                'verbose_name_plural': 'Состав по слоям',
                'verbose_name': 'Состав по слоям',
            },
        ),
        migrations.CreateModel(
            name='ExtraSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ширина')),
                ('length', models.IntegerField(blank=True, default=None, null=True, verbose_name='Длина')),
                ('price', models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ExtraProduct')),
            ],
        ),
    ]
